# Generated by Django 4.2.7 on 2025-07-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embedding',
            options={'verbose_name': 'Векторное представление', 'verbose_name_plural': 'Векторные представления'},
        ),
        migrations.AlterField(
            model_name='embedding',
            name='embedding_vector',
            field=models.JSONField(verbose_name='Векторное представление'),
        ),
    ]
