# Generated by Django 4.2.7 on 2025-07-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_embeddings_to_vectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Токен персонального бота для клиентов салона', max_length=255, verbose_name='Токен Telegram бота салона'),
        ),
        migrations.AddField(
            model_name='salon',
            name='telegram_bot_username',
            field=models.CharField(blank=True, help_text='Username бота для клиентов (без @)', max_length=100, verbose_name='Username Telegram бота'),
        ),
    ]
