# Generated by Django 4.2.7 on 2025-07-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_salon_bot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='API ключ для интеграции с OpenAI', max_length=255, verbose_name='OpenAI API ключ'),
        ),
    ]
